name: Home Build

on:
  push:
    paths:
      - 'home/**'
      - 'users/*/home/**'
  pull_request:
    paths:
      - 'home/**'
      - 'users/*/home/**'

jobs:
  build_n_push:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: my-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build system
        run: nix-build $GITHUB_WORKSPACE -A home
